# Generated by Django 2.0.7 on 2018-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0003_auto_20160715_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url_name',
            field=models.CharField(max_length=65, verbose_name='Url Name'),
        ),
    ]
